[workspace]
resolver = "2"
members = ["./lib", "./rusttopo2geo"]

[workspace.package]
# Version 1.65 is required as clap_derive v4.4.2 needs it.
rust-version = "1.85"
edition = '2024'

[workspace.dependencies]
geo = "0.31.0"
geo-types = "~0.7"
serde_json = "1.0.143"
serde = "~1"
topojson = "~0.5"
